### ISSUE TITLE
--exclude is not exluding

### ISSUE THREAD

**Issue by yazoooo** [raphaelmansuy/code2prompt#5] opened 2024-06-29 17:17 UTC
BTW. Really helpful tool!  It does exactly what I want. I pushed this all into gemini 1.5 flash and it was able to discuss my project intelligently.

I have tried specifying the --exclude in both the command line and inside the configuration file.  I also also tried both formats in the examples "*/tests/*" and "tests/*.

{
  "suppress_comments": true,
  "line_number": true,
  "encoding": "cl100k_base",
  "filter": "*.py,*.js",
  "exclude": "tests/*,prototypes/*",
  "tokens": true
}

(hals-pen-py3.10) yazoooo@yazoooo-dev:~/PycharmProjects/hals-pen$ code2prompt --output code2prompt.txt --gitignore .gitignore --tokens --path .

Beginning of output
 Table of Contents
- prototypes/bedrock_anthropic_3.py
- prototypes/pyqt6_test_1.py
- prototypes/pyqt6_scene_editor_test.py
- prototypes/bedrock_anthropic_2.py
- prototypes/bedrock_anthropic_1.py
- prototypes/openai_api_test_1.py
- prototypes/print_fonts.py
- prototypes/scrolling_widgets.py
- prototypes/openai_api_test_2.py
- prototypes/pyqt6_test_2.py
- prototypes/conversation_editor.py
- tests/__init__.py
- tests/BaseTest.py
- tests/ui/__init__.py
- tests/ui/test_plot_node_utils.py
- tests/ui/test_project_controller.py
- tests/ui/test_project_tree_model.py
- tests/persistance/__init__.py
- tests/persistance/test_story_io.py
- tests/utils/__init__.py
- tests/utils/test_image_utils.py
- tests/story/__init__.py
- tests/story/test_story_nodes.py
- tests/story/test_story_project.py
- tests/ai/__init__.py
- tests/ai/test_openai_client.py
- tests/ai/test_ai_client.py
- tests/ai/test_ai_chat_builder.py
- tests/ai/test_google_gemini_client.py
- hals_pen/__init__.py
- hals_pen/main.py
- hals_pen/ui/tab_area.py
- hals_pen/ui/project_tab.py
- hals_pen/ui/__init__.py
- hals_pen/ui/project_controller.py
- hals_pen/ui/navigation_pane.py
- hals_pen/ui/project_tree_view.py

**Comment by raphaelmansuy** [comment] 2024-07-03 02:20
The issue is fixed in version 0.6.7

Reinstall using pipx install code2prompt --force

**Closed by raphaelmansuy** 2024-07-03 02:20 UTC
